### ISSUE TITLE
Updated Dublast

### ISSUE THREAD

**Issue by Nico-Duduf** [Thane5/quickrenderbuttons#1]
Hello!

Your addon is a great idea ;)

I just wanted to let you know I've just made an important update to dublast (for metadata options, and more importantly including annotations into the playblast).

One suggestion: instead of including dublast in your add-on (if you've not made major changes), you could check if dublast is installed, and if so, display its operator; that could be easier for you to maintain, with the downside that the user would have to install both addons.

To check an addon availability I use this:

```py
def isDuBlastEnabled():
    addons = bpy.context.preferences.addons
    for addon in addons:
        if addon.module == 'dublast':
            return True
    return False
```

Cheers!

**Comment by Thane5** [comment]
I was hesitant to implement this because i already had forgotten how most of blender scripting works... anyways, with some extra help i finally managed to do it, plus cleaned up tons of obsolete lines. 

I removed my copy of DuBlast and now the Playblast button is invisible unless DuBlast is installed.
